# Generated by Django 6.0 on 2025-12-10 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page', models.CharField(max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
