# Generated by Django 6.0 on 2025-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hub', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
