# Generated by Django 6.0 on 2025-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hub', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
