"""
Django settings for project_hub project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", "").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django_growth',
    'visitor_stats',
    'app_hub',
]

VISITOR_STATS_BASE_TEMPLATE = 'base.html'
VISITOR_STATS_HOME_URL_NAME = 'home'

SITE_ID = 1

# Trust the X-Forwarded headers from the proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SECURE_SSL_REDIRECT = True
PREPEND_WWW = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_growth.context_processors.growth',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_hub.wsgi.application'


GROWTH = {
    "GTM_ID": config('GTM_ID'),
    "SITE_NAME": config('SITE_NAME'),
    "ENV": "production" if not DEBUG else "development",
    "GOOGLE_VERIFICATION": config('GOOGLE_VERIFICATION'),
    "SITEMAPS": {
        # "pages": PagesSitemap,
        # "blog": BlogSitemap,
    },
    # Site-wide default for Open Graph / Twitter image when a page omits og_image:
    "DEFAULT_OG_IMAGE": "https://onorio.dev/static/img/onorio_dejesus.png",
    # Optional robots behavior (defaults are safe for local dev):
    # "ROBOTS_DISALLOW_ALL": True,
    # "ROBOTS_INCLUDE_SITEMAP": True,
    # Optional SEO / social (all omitted or empty = tag not rendered):
    "META_VIEWPORT": "width=device-width, initial-scale=1.0",
    "META_KEYWORDS": "Onório de Jesus, Onorio de Jesus, ICT Officer, Quality Assurance, Developer Timor-Leste",
    "META_AUTHOR": "Onório de Jesus",
    "OG_LOCALE": "en_US",
    "TWITTER_SITE": "@AfonsoOnorio",
    "TWITTER_CREATOR": "@AfonsoOnorio",
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Contact email settings using Resend
RESEND_API_KEY = config('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
CONTACT_RECEIVER_EMAIL = config('CONTACT_RECEIVER_EMAIL')

# Local settings
try:
    from .local_settings import *
except ImportError:
    pass
